In [2]:
# Consider the below code to answer further questions:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)


### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
# Yes, there is a difference in the data types of list_ and array_list. list_ is a Python list, whereas array_list is a NumPy array.
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data types of both variables
print(f"The data type of list_ is: {type(list_)}")
print(f"The data type of array_list is: {type(array_list)}")


The data type of list_ is: <class 'list'>
The data type of array_list is: <class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [4]:
# Print the data type of each element in list_
print("Data types of each element in list_:")
for elem in list_:
    print(type(elem))

# Print the data type of each element in array_list
print("Data types of each element in array_list:")
for elem in array_list:
    print(type(elem))


Data types of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int) <br>
Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print the data type of each element in list_
print("Data types of each element in list_:")
for elem in list_:
    print(type(elem))

# Print the data type of each element in array_list
print("Data types of each element in array_list after conversion:")
for elem in array_list:
    print(type(elem))


Data types of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of each element in array_list after conversion:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [6]:
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)


### Q4. Write a code to find the following characteristics of variable, num_array: 
1. shape
2. size

In [7]:
# Q4. (i) Shape of num_array
shape = num_array.shape
print(f"Shape of num_array: {shape}")

Shape of num_array: (2, 3)


In [9]:
# Q4. (ii) Size of num_array
size = num_array.size
print(f"Size of num_array: {size}")

Size of num_array: 6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).] 

In [11]:
# Create a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))
print("3x3 matrix of zeros:")
print(zero_matrix)

3x3 matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [12]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 identity matrix:")
print(identity_matrix)

5x5 identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
